name: Documenter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      # replace value on .env .aiimpact/.env
      - name: Replace value on .env
        run: |
          sed -i "s|Llms__GPT_4_128k__Config__OpenAiKey=.*|Llms__GPT_4_128k__Config__OpenAiKey=${{ secrets.GPT_4_KEY }}|" .aiimpact/.env

      # add docker compose task
      - name: Docker Compose
        run: docker-compose up -d
        working-directory: .aiimpact

      - name: Docker Compose
        run: docker-compose down
        working-directory: .aiimpact
      
      
          
