name: Documenter

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Get issue attachments
        id: get_attachments
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body' > issue_body.txt
          cat issue_body.txt
          ATTACHMENTS=$(grep -Eo '\(https://github.com/[^ ]+\)' issue_body.txt | sed 's/[()]//g')
          echo "attachments=$ATTACHMENTS" >> $GITHUB_ENV

      - name: Download attachments
        run: |
          mkdir -p attachments
          for url in ${{ env.attachments }}; do
            wget --header="Authorization: token ${{ secrets.GH_TOKEN }}" -P attachments $url
          done
          cd attachments
          ls -la

      
      - name: Unzip attachments
        run: |
          for file in attachments/*.zip; do
            unzip -o $file -d attachments/
          done
          cd attachments
          rm *.zip



      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      # replace value on .env .aiimpact/.env
      # - name: Replace value on .env
      #   run: |
      #     sed -i "s|Llms__GPT_4_128k__Config__OpenAiKey=.*|Llms__GPT_4_128k__Config__OpenAiKey=${{ secrets.GPT_4_KEY }}|" /home/azureuser/aiimpact/.aiimpact/.env

      # add docker compose task
      # - name: Docker Compose
      #   run: docker compose up -d
      #   working-directory: /home/azureuser/aiimpact/.aiimpact
      
      
      - name: Execute Curl Command
        run: |
          FILES=""
          for file in attachments/*; do
            if [ "$file" != "attachments/*.zip" ]; then
              FILES="$FILES --form files=@$file"
            fi
          done
          echo $FILES
          eval "curl --location 'http://localhost:4000/ai/document' \
            --form 'RunName=Demo_02' \
            $FILES \
            --form 'jobName=DemoDocCreator' \
            --form 'DocumentationFormat=markdown' \
            --form 'DiagramFormat=Mermaid' \
            --form 'SourceCodeLanguage=Java' \
            --form 'DocumentationAudience=tester' \
            --form 'PromptId=DocCreator__DocumentCode_V3' \
            --form 'TargetExtension=md' \
            --form 'Llm=GPT_4_128k' \
            --form 'AdditionalInstructions=Generate all answers in Brazilian Portuguese'"


      # - name: Docker Compose
      #   run: docker compose down
      #   working-directory: /home/azureuser/aiimpact/.aiimpact
      
      
          
