name: Documenter

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get issue attachments
        id: get_attachments
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments 

      - name: Download attachments
        run: |
          mkdir -p attachments
          for url in ${{ env.attachments }}; do
            wget -P attachments $url
          done
          cd attachments
          ls -la




      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      # replace value on .env .aiimpact/.env
      - name: Replace value on .env
        run: |
          sed -i "s|Llms__GPT_4_128k__Config__OpenAiKey=.*|Llms__GPT_4_128k__Config__OpenAiKey=${{ secrets.GPT_4_KEY }}|" .aiimpact/.env

      # add docker compose task
      - name: Docker Compose
        run: docker-compose up -d
        working-directory: .aiimpact

      # - name: Execute Curl Command
      #   run: |
      #     curl --location 'http://localhost:4000/ai/document' \
      #     --form 'RunName="Demo_02"' \
      #     --form 'files=@"/Users/arruda/projects/demo-java-citi/src/main/java/com/scalesec/vulnado/User.java"' \
      #     --form 'jobName="DemoDocCreator"' \
      #     --form 'DocumentationFormat="markdown"' \
      #     --form 'DiagramFormat="Mermaid"' \
      #     --form 'SourceCodeLanguage="Java"' \
      #     --form 'DocumentationAudience="tester"' \
      #     --form 'PromptId="DocCreator__DocumentCode_V3"' \
      #     --form 'TargetExtension="md"' \
      #     --form 'Llm="GPT_4_128k"' \
      #     --form 'AdditionalInstructions="Generate all answers in Brazilian Portuguese"'

      - name: Docker Compose
        run: docker-compose down
        working-directory: .aiimpact
      
      
          
