name: Documenter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: $DOCKER_REGISTRY
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
          
